apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  labels:
    app: todo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: k3d-test-app-registry:5050/todo-frontend:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: todo-frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
  selector:
    app: todo-frontend

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-frontend
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-frontend
                port:
                  number: 80
